services:
  config-dist:
    image: alpine:latest
    container_name: config-dist
    environment:
      WEB_URL: https://trulyben.com
      KEYCLOAK_URL: https://keycloak.trulyben.com/*
      KEYCLOAK_HOSTNAME: keycloak.trulyben.com
      KEYCLOAK_REALM: tb-apps
      KEYCLOAK_WEB_CLIENT_ID: tb-web
      KEYCLOAK_WEB_REDIRECT_URI: https://trulyben.com/home
      KEYCLOAK_GAMES_CLIENT_ID: tb-games
      KEYCLOAK_GAMES_REDIRECT_URI: https://games.trulyben.com/home
    volumes:
      - keycloak_certs:/etc/x509
      - keycloak_config:/opt/keycloak/data/import
      - web_config:/usr/share/nginx/html/assets
      - ./config:/tmp
    command: > 
      sh -c '
        apk add --no-cache gettext openssl &&

        # generate certs
        mkdir -p /etc/x509 &&
        openssl req -x509 -newkey rsa:4096 -keyout /etc/x509/key.pem -out /etc/x509/cert.pem -days 365 -nodes -subj "/CN=$$KEYCLOAK_HOSTNAME" &&
        chown 1000:1000 /etc/x509/key.pem /etc/x509/cert.pem &&
        chmod 640 /etc/x509/key.pem /etc/x509/cert.pem &&

        # generate configs
        envsubst < /tmp/keycloak-config.json.template > /opt/keycloak/data/import/config.json &&
        envsubst < /tmp/web-config.json.template > /usr/share/nginx/html/assets/config.json
      '

  web:
    image: itsbensmall/tb-web:latest
    container_name: web
    depends_on:
      config-dist:
        condition: service_completed_successfully
    labels:
      - "com.centurylinklabs.watchtower.scope=tb"
    volumes:
      - "web_config:/usr/share/nginx/html/assets"
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app

  keycloak-postgres:
    image: postgres:latest 
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql
    restart: unless-stopped
    ports:
      - "8082:5432"
    networks:
      - auth
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KEYCLOAK_POSTGRES_USER} -d keycloak || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    depends_on:
      config-dist:
        condition: service_completed_successfully
      keycloak-postgres:
        condition: service_healthy
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}

      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      KC_HTTPS_PORT: 8443
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/cert.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/key.pem

      KC_HOSTNAME: keycloak.trulyben.com
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_PROXY: edge
      KC_HTTP_ENABLED: "false"
    volumes:
      - keycloak_config:/opt/keycloak/data/import
      - keycloak_certs:/etc/x509:ro
    restart: unless-stopped
    ports:
      - "8443:8443"
    networks:
      - auth
      - app
    command: start --import-realm

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    labels:
      - "com.centurylinklabs.watchtower.scope=tb"
    environment:
      DOCKER_API_VERSION: 1.44
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_URL: ${WATCHTOWER_SHOUTRRR_WEBHOOK}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: 
      - --interval=30
      - --scope=tb

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token $CLOUDFLARE_TUNNEL_TOKEN
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}

networks:
  app:
    driver: bridge
  auth:
    driver: bridge

volumes:
  keycloak_postgres_data:
  keycloak_certs:
  keycloak_config:
  web_config: